"""empty message

Revision ID: 68b89f39d8bd
Revises: 704e89cb8f64
Create Date: 2018-03-23 10:06:59.502533

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '68b89f39d8bd'
down_revision = '704e89cb8f64'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('restaurant', sa.Column('types', sa.VARCHAR(length=20), nullable=False))
    op.alter_column('restaurant', 'type',
               existing_type=sa.VARCHAR(length=20),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('restaurant', 'type',
               existing_type=sa.VARCHAR(length=20),
               nullable=False)
    op.drop_column('restaurant', 'types')
    # ### end Alembic commands ###
