"""empty message

Revision ID: 723e6d09380e
Revises: 
Create Date: 2018-03-16 21:36:31.225434

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '723e6d09380e'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('raters',
    sa.Column('userid', sa.Integer(), nullable=False),
    sa.Column('email', sa.VARCHAR(length=30), nullable=False),
    sa.Column('name', sa.VARCHAR(length=20), nullable=False),
    sa.Column('join_date', sa.Date(), nullable=False),
    sa.PrimaryKeyConstraint('userid')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('raters')
    # ### end Alembic commands ###
