"""empty message

Revision ID: b42e30d1f45d
Revises: e7623f119bad
Create Date: 2018-03-17 14:36:14.182690

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b42e30d1f45d'
down_revision = 'e7623f119bad'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('rater', sa.Column('name', sa.VARCHAR(length=15), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('rater', 'name')
    # ### end Alembic commands ###
