"""empty message

Revision ID: cd61ed78e47d
Revises: 
Create Date: 2018-03-14 22:18:16.175015

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cd61ed78e47d'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('resto',
    sa.Column('restaurantid', sa.Integer(), nullable=False),
    sa.Column('name', sa.VARCHAR(length=20), nullable=False),
    sa.Column('type', sa.VARCHAR(length=20), nullable=False),
    sa.Column('url', sa.VARCHAR(length=50), nullable=True),
    sa.PrimaryKeyConstraint('restaurantid')
    )
    op.create_table('locate',
    sa.Column('locationid', sa.Integer(), nullable=False),
    sa.Column('first_open_date', sa.Date(), nullable=False),
    sa.Column('manager_name', sa.VARCHAR(length=30), nullable=False),
    sa.Column('phone_number', sa.VARCHAR(length=10), nullable=False),
    sa.Column('street_address', sa.VARCHAR(length=30), nullable=False),
    sa.Column('hour_open', sa.VARCHAR(length=5), nullable=False),
    sa.Column('hour_close', sa.VARCHAR(length=5), nullable=False),
    sa.Column('restaurantid', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['restaurantid'], ['resto.restaurantid'], ),
    sa.PrimaryKeyConstraint('locationid')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('locate')
    op.drop_table('resto')
    # ### end Alembic commands ###
