"""empty message

Revision ID: 72fbffec5542
Revises: b1e3404a9105
Create Date: 2018-03-19 16:34:31.806980

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '72fbffec5542'
down_revision = 'b1e3404a9105'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('rater',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('email', sa.VARCHAR(length=30), nullable=False),
    sa.Column('name', sa.VARCHAR(length=15), nullable=False),
    sa.Column('join_date', sa.Date(), nullable=False),
    sa.Column('rater_type', sa.VARCHAR(length=15), nullable=False),
    sa.Column('reputation', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.drop_table('menuitem')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('menuitem',
    sa.Column('item_id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(length=30), autoincrement=False, nullable=False),
    sa.Column('category', sa.VARCHAR(length=15), autoincrement=False, nullable=False),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('price', sa.NUMERIC(precision=5, scale=2), autoincrement=False, nullable=False),
    sa.Column('restaurantid', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['restaurantid'], ['restaurant.restaurantid'], name='menuitem_restaurantid_fkey'),
    sa.PrimaryKeyConstraint('item_id', name='menuitem_pkey')
    )
    op.drop_table('rater')
    # ### end Alembic commands ###
