"""empty message

Revision ID: b05d2b3e6392
Revises: d80f73d515e0
Create Date: 2018-03-19 15:25:23.770157

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b05d2b3e6392'
down_revision = 'd80f73d515e0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('rater',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('email', sa.VARCHAR(length=30), nullable=False),
    sa.Column('name', sa.VARCHAR(length=15), nullable=False),
    sa.Column('join_date', sa.Date(), nullable=False),
    sa.Column('rater_type', sa.VARCHAR(length=15), nullable=False),
    sa.Column('reputation', sa.Integer(), nullable=False),
    sa.CheckConstraint('reputation', name='reputation >= 1 AND reputation <= 5'),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_table('rating',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('price', sa.Integer(), nullable=False),
    sa.Column('food', sa.Integer(), nullable=False),
    sa.Column('mood', sa.Integer(), nullable=False),
    sa.Column('staff', sa.Integer(), nullable=False),
    sa.Column('comments', sa.TEXT(), nullable=True),
    sa.Column('restaurantid', sa.Integer(), nullable=False),
    sa.CheckConstraint('food', name='food >= 1 AND food <= 5'),
    sa.CheckConstraint('mood', name='mood >= 1 AND mood <= 5'),
    sa.CheckConstraint('price', name='price >= 1 AND price <= 5'),
    sa.CheckConstraint('staff', name='staff >= 1 AND staff <= 5'),
    sa.ForeignKeyConstraint(['restaurantid'], ['restaurant.restaurantid'], ),
    sa.ForeignKeyConstraint(['user_id'], ['rater.user_id'], ),
    sa.PrimaryKeyConstraint('user_id', 'date')
    )
    op.create_table('ratingitem',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('item_id', sa.Integer(), nullable=False),
    sa.Column('rating', sa.Integer(), nullable=False),
    sa.Column('comment', sa.Text(), nullable=False),
    sa.CheckConstraint('rating', name='rating >= 1 AND rating <= 5'),
    sa.ForeignKeyConstraint(['item_id'], ['menuitem.item_id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['rater.user_id'], ),
    sa.PrimaryKeyConstraint('user_id', 'date', 'item_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('ratingitem')
    op.drop_table('rating')
    op.drop_table('rater')
    # ### end Alembic commands ###
