"""empty message

Revision ID: b321f9c333dd
Revises: b8403ab84777
Create Date: 2018-03-23 10:12:05.425980

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b321f9c333dd'
down_revision = 'b8403ab84777'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('restaurant', 'types',
               existing_type=sa.VARCHAR(length=20),
               nullable=False)
    op.drop_column('restaurant', 'type')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('restaurant', sa.Column('type', sa.VARCHAR(length=20), autoincrement=False, nullable=False))
    op.alter_column('restaurant', 'types',
               existing_type=sa.VARCHAR(length=20),
               nullable=True)
    # ### end Alembic commands ###
