"""empty message

Revision ID: b8403ab84777
Revises: 68b89f39d8bd
Create Date: 2018-03-23 10:07:49.592214

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b8403ab84777'
down_revision = '68b89f39d8bd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('restaurant', sa.Column('types', sa.VARCHAR(length=20), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('restaurant', 'types')
    # ### end Alembic commands ###
