"""empty message

Revision ID: ef713f38bcd1
Revises: 87b921e086f1
Create Date: 2018-03-17 14:38:15.701821

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ef713f38bcd1'
down_revision = '87b921e086f1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('rater',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('email', sa.VARCHAR(length=30), nullable=False),
    sa.Column('name', sa.VARCHAR(length=15), nullable=False),
    sa.Column('join_date', sa.Date(), nullable=False),
    sa.Column('rater_type', sa.VARCHAR(length=15), nullable=False),
    sa.Column('reputation', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_table('menuitem',
    sa.Column('item_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.VARCHAR(length=30), nullable=False),
    sa.Column('category', sa.VARCHAR(length=15), nullable=False),
    sa.Column('description', sa.TEXT(), nullable=False),
    sa.Column('price', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('restaurantid', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['restaurantid'], ['restaurant.restaurantid'], ),
    sa.PrimaryKeyConstraint('item_id')
    )
    op.create_table('rating',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('price', sa.Integer(), nullable=False),
    sa.Column('food', sa.Integer(), nullable=False),
    sa.Column('mood', sa.Integer(), nullable=False),
    sa.Column('staff', sa.Integer(), nullable=False),
    sa.Column('comments', sa.TEXT(), nullable=True),
    sa.Column('restaurantid', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['restaurantid'], ['restaurant.restaurantid'], ),
    sa.ForeignKeyConstraint(['user_id'], ['rater.user_id'], ),
    sa.PrimaryKeyConstraint('user_id', 'date')
    )
    op.create_table('ratingitem',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('item_id', sa.Integer(), nullable=False),
    sa.Column('rating', sa.Integer(), nullable=False),
    sa.Column('comment', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['item_id'], ['menuitem.item_id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['rater.user_id'], ),
    sa.PrimaryKeyConstraint('user_id', 'date', 'item_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('ratingitem')
    op.drop_table('rating')
    op.drop_table('menuitem')
    op.drop_table('rater')
    # ### end Alembic commands ###
